### ISSUE TITLE
dsnp.createNewDSNPRegistration returning a URI instead of a Registration

### ISSUE THREAD

**Issue by claireolmstead** [LibertyDSNP/sdk-ts#176]
### Steps to reproduce
When you call `dsnp.createNewDSNPRegistration`. 

### Expected behavior
You would expect to receive an object of type `Registration`.

### Actual behavior
Instead, a URI is returned.

### Any other comments?
I would like to receive a registration instead of a URI upon create registration becuase that data type is reflecive of what was just made.  When we receive a URI we would have to call another function to get what we just created, which seems like an extra step, especially becuase the new registration is available to be returned in the SDK function.

**Comment by wilwade** [comment]
Fixed in #179
